import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "../globals.scss";
const karlaFont = Karla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={karlaFont.className}>{children}</body>
    </html>
  );
}
